version: "3.4"

services:
  drupal:
    image: drupal:8-apache
    ports:
      - "80:80"
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - ./themes:/var/www/html/themes
      - /var/www/html/sites
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 20s
        order: stop-first

  postgres:
    image: postgres:10
    secrets:
      - psql_pass
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql_pass
    volumes:
      - drupal-data:/var/lib/postgresql/data
    restart: always

secrets:
  psql_pass:
    external: true

volumes:
  drupal-data: